pipeline:
  name: gk-e2e-cicd-pipeline
  identifier: gke2ecicdpipeline
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags:
    ai_generated: "true"
  properties:
    ci:
      codebase:
        connectorRef: gkalipallinewgitconnector
        repoName: Ekart-gk
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: flex
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: mvn clean package -DskipTests -Dmaven.main.skip=false
                  timeout: 10m
              - step:
                  type: Run
                  name: Verify_Directory_Structure
                  identifier: Verify_Directory_Structure
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Bash
                    command: |
                      # Check if target/classes directory exists
                      if [ ! -d "target/classes" ]; then
                        echo "target/classes directory does not exist, creating it"
                        mkdir -p target/classes
                        
                        # If we have cached artifacts, try to extract class files
                        if [ -d "target" ] && [ -f "target/*.jar" ]; then
                          echo "Found JAR files, extracting class files to target/classes"
                          # Extract class files from JAR to target/classes
                          for jar in target/*.jar; do
                            jar xf "$jar" -C target/classes .
                          done
                        fi
                      else
                        echo "target/classes directory exists"
                      fi

                      # List directory contents for verification
                      echo "Directory structure:"
                      ls -la target/

                      # Export success status
                      export DIRECTORY_CHECK_STATUS="success"
                    outputVariables:
                      - name: DIRECTORY_CHECK_STATUS
                  timeout: 10m
              - step:
                  type: BuildAndPushGAR
                  name: BuildAndPushGAR_1
                  identifier: BuildAndPushGAR_1
                  spec:
                    connectorRef: gkgcpconnectorv2latest
                    host: us-central1-docker.pkg.dev
                    projectID: gkalipalli1
                    imageName: ekart-repo/ekart
                    tags:
                      - latest
              - step:
                  type: Sonarqube
                  name: Sonarqube_1
                  identifier: Sonarqube_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                    auth:
                      access_token: squ_1f09794e1fdce12d294e5f27054fc110fb9d4a04
                      domain: http://34.28.80.104:9000
                      ssl: true
                    tool:
                      java:
                        libraries: target/*.jar
                        binaries: target/classes,target
                      project_key: ekart-sonar
                  timeout: 10m
            rollbackSteps: []
          buildIntelligence:
            enabled: true
    - stage:
        name: CD
        identifier: CD
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: gksvcnew
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
            gitBranch: main
          environment:
            environmentRef: ekartprod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: gkinfranew
          execution:
            steps:
              - step:
                  type: K8sRollingDeploy
                  name: K8sRollingDeploy_2
                  identifier: K8sRollingDeploy_2
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  description: This pipeline was updated by Harness AI on 2026-01-09 13:56:20 UTC by Gowtham.
